# Generated by Django 6.0.3 on 2026-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='total_tokens_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='total_tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toollog',
            name='tokens_input',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toollog',
            name='tokens_output',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toollog',
            name='tokens_saved',
            field=models.IntegerField(default=0),
        ),
    ]
