# Generated by Django 6.0.3 on 2026-03-29 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0002_session_total_tokens_saved_session_total_tokens_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('last_indexed', models.DateTimeField(blank=True, null=True)),
                ('symbol_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('scores_json', models.TextField()),
                ('average_score', models.FloatField()),
                ('recommendations', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_qualities', to='mcp_server.session')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=1024)),
                ('symbol_type', models.CharField(choices=[('class', 'Class'), ('function', 'Function'), ('method', 'Method'), ('module', 'Module')], max_length=20)),
                ('file_path', models.CharField(max_length=1024)),
                ('line_number', models.IntegerField()),
                ('docstring', models.TextField(blank=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='mcp_server.repository')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('calls', 'Calls'), ('inherits', 'Inherits from'), ('contains', 'Contains')], max_length=20)),
                ('from_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='mcp_server.symbol')),
                ('to_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='mcp_server.symbol')),
            ],
        ),
    ]
